//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistStockDetail
    {
        public int HistID { get; set; }
        public int ID { get; set; }
        public int sellinValue { get; set; }
        public int quality { get; set; }
        public System.DateTime Createdatetime { get; set; }
    
        public virtual StockDetail StockDetail { get; set; }
    }
}
