//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockDetail()
        {
            this.HistStockDetails = new HashSet<HistStockDetail>();
        }
    
        public int ID { get; set; }
        public int sellinValue { get; set; }
        public int quality { get; set; }
        public int categoryID { get; set; }
        public System.DateTime Createdatetime { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
        public Nullable<int> NoOfPieces { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistStockDetail> HistStockDetails { get; set; }
    }
}
